const cards = ["cocktail_ireland.jpg",
    "cycling-wollongong.jpg",
    "dinner-en-blanc.jpg",
    "dinner-flinders.jpg",
    "fantasy.jpg",
    "ferris.jpg",
    "glitter.jpg",
    "ice-skating.jpg",
    "in-a-jar.jpg",
    "india-elephant.jpg",
    "india-somewhere.jpg",
    "jess-wedding.jpg",
    "kandy-wedding.jpg",
    "kayak-trip.jpg",
    "megalong-valley-wine.jpg",
    "melbourne-iron-man.jpg",
    "mount-solitary.jpg",
    "mountain-scotland.jpg",
    "mountains.jpg",
    "pelicanos_greece.jpg",
    "snowy.jpg",
    "tassie.jpg",
    "tom_birthday.jpg",
    "toy-story.jpg",
    "wedding-sigrid.jpg",
    "wedding-sigrid3.jpg",
    "wedding-sigrid-2.jpg",
    "wedding_ireland.jpg",
    "windy_greece.jpg",
    "wine_cycle.jpg"
];

export default cards;
